version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: bookstore
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
